# QF627 Pre-Course Workshop | Introduction to Programming

## Lesson 2 | An Introduction to `NumPy` | `RE`view

> In the previous lesson, you have learned about `methods and functions` that are available in built-in Python, along with variables and data types.

> First, let us begin with some basic built-in Python that you need to fully understand before we proceed.

> Here's a quick reminder regarding the useful hotkeys for scripting on Jupyter Notebook :)

- `a` inserts a cell above 
- `b` inserts a cell below
- `dd` (double d) deletes a cell 
- `esc` jumps out of the cell
- `return/enter` gets into the cell
- `m` makes your cell markdown
- `y` makes your cell code
- `shift + control + -` splits the cell
- `shift + m` merges the cells
- `shift + l` adds line numbers into the cell

> Now you will start learning about how to use `packages`.

> As Python is open-source language, using the humongous ecosystem of packages will help you work more efficiently.

> A `package is a collection of Python modules and scripts` giving you new data types, functions, and methods.


### How to `install` a ***package***?

> To use a package, you need to download it first.

> Let's use the command `pip3 install target_package` so that you can install packages of your interest.

> For downloading a package, you need to do this just once, yet you should import in your workspace whenever you wish to use it.

> The command below will load the NumPy package into Python for your use.

> `numpy`: numerical computation

In [1]:
# !pip install numpy


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


> `pandas`: data transformation & manipulation for tabular data

In [3]:
# !pip install pandas


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


> `matplotlib`: matlab-like plotting

In [4]:
# !pip install matplotlib


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


> `seaborn`: visualization for modeling information 

In [5]:
# !pip install seaborn


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


> `statsmodels`: Modeling for Explanation Purposes (B-hat Question; Causal Inference)

In [6]:
# !pip install statsmodels


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


> `scikit-learn`: Modeling for Prediction Purposes (Y-hat Question; Machine Learning)

In [7]:
# !pip install scikit-learn


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


### Setting dependencies

In [1]:
%whos

Interactive namespace is empty.


In [2]:
import numpy

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
numpy      module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [4]:
import numpy as np

In [5]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy      module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [6]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

***Wait, why do we use alias here (i.e., as `np`)? ?*** 

> As you will see below, 

- To access the array() function, you need to use np.array() to indicate that the function is from the NumPy package.

> Yes, the reason why we have used np as alias is to minimize our typing task.

### The Basics

> Using `NumPy`, you can create a new data type called `array`.

> Why use data type `array`?

**`array` is useful for financial analysis because...**

- array `stores` data more efficiently

- array `performs` faster than built-in Python lists in terms of computations (access in reading and writing items faster as the package is optimized for numerical analyses)

- array `shows` better performance with relatively larger datasets

- array, most importantly, **`enables` you to utilize `array-related functions`**--you can perform statistical modelling and visualization easier, which is critical for financial analysis.





> **A good way to understand about the usefulness of NumPy is to compare array with list (yes, that list that you learned in the previous lesson).**

#### Differences 1. Arrays can contain only a single data type (unlike lists).

In [7]:
a_list =\
    ["QF627",
     2024,
     "Yes",
     True]

In [8]:
a_list

['QF627', 2024, 'Yes', True]

In [9]:
type(a_list)

list

In [10]:
len(a_list) == 4

True

In [11]:
type(a_list[0]
    )

str

In [12]:
type(a_list[-1]
    )

bool

> As you will see below, arrays in NumPy will convert the elements in the list to the most compatible data types.

```python

an_array =\
(
    np
    .array(['QF627', 2024, 'Yes', True]
          )
)

In [13]:
an_array =\
(
    np
    .array(a_list
          )
)

In [14]:
type(an_array)

numpy.ndarray

In [15]:
%whos

Variable   Type       Data/Info
-------------------------------
a_list     list       n=4
an_array   ndarray    4: 4 elems, type `<U21`, 336 bytes
np         module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy      module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [16]:
# Here are lists.
earnings_list = [10.09, 10.28, 2.21, 6.19, 8.24]
prices_list = [99.98, 87.68, 154.23, 162.12, 121.11]

> How would you make objects `earnings` and `prices` arrays?

In [17]:
earnings_ARRAY = np.array(earnings_list)
prices_ARRAY = np.array(prices_list)

print(earnings_ARRAY);print(prices_ARRAY)

[10.09 10.28  2.21  6.19  8.24]
[ 99.98  87.68 154.23 162.12 121.11]


#### Differences 2. Arrays have different ways of operations (than lists).

> Let's see how lists behave first.

In [18]:
pe_ratio_list = prices_list + earnings_list
print(pe_ratio_list)

[99.98, 87.68, 154.23, 162.12, 121.11, 10.09, 10.28, 2.21, 6.19, 8.24]


> The two objects were merely concatenated. That's not what we want...

In [19]:
pe_ratio_ARRAY = prices_ARRAY / earnings_ARRAY
print(pe_ratio_ARRAY)

[ 9.90882061  8.52918288 69.78733032 26.19063005 14.69781553]


> ***Arrays allow for efficient numerical manipulation of its elements.***

> Let's calculate `the dollar amount an investor can expect to invest in a company to receive one dollar of that company’s earnings`--yes, the `price to earnings ratio`--using two arrays, earnings_array and prices_array above.

In [22]:
len(prices_ARRAY)

5

In [23]:
len(prices_list)

5

In [21]:
## if you wish to run vectorized computation with built-in Python list

# pe_ratio_array = prices_array / earnings_array

# print(pe_ratio_array)

element_wise_list = []

for first_object, second_object in zip(prices_list, earnings_list):
    element_wise_list.append(first_object + second_object)

In [24]:
len(element_wise_list)

5

In [25]:
element_wise_list

[110.07000000000001, 97.96000000000001, 156.44, 168.31, 129.35]

In [26]:
list_A = [1, 2, 3]
list_B = [4, 5, 6]

In [27]:
list_A + list_B

[1, 2, 3, 4, 5, 6]

In [28]:
result_element_wise =\
    [a + b for a, b in zip(list_A, list_B)
    ]

result_element_wise

[5, 7, 9]

> You could see here that arrays perform `element-wise mathematical operations`.

#### Indexing, Subsetting, Filtering, & Slicing: Similarities between `array` and `list`

> We have seen differences between arrays and lists.

> Here are also similarities.

> `similarities`

In [29]:
earnings_list

[10.09, 10.28, 2.21, 6.19, 8.24]

In [31]:
earnings_list_SUBSET = earnings_list[1:-1]

In [32]:
earnings_ARRAY[1:-1] # returns array([10.28, 2.21, 6.19])

array([10.28,  2.21,  6.19])

In [33]:
earnings_ARRAY_SUBSET = earnings_ARRAY[1:-1]

> `differences`

In [35]:
earnings_ARRAY[1:4] == earnings_ARRAY_SUBSET # returns array([True, True, True])

array([ True,  True,  True])

In [36]:
earnings_list[1:4] == earnings_list_SUBSET # returns True

True

In [37]:
len(earnings_ARRAY[1:4] == earnings_ARRAY_SUBSET)

3

> Please address the error message above.

### Arrays in NumPy can be `multi`dimensional.

![](ndim.png)
#### How to add image (CLICK HERE TWICE)

> A common form of financial data comes with a rectangular form of data that contains rows and columns. 

> Such data can be represented with two-dimensional arrays.

> To create a two-dimensional array using NumPy, you can use the same function array().

> Instead of providing a single list as your input, let's pass in a list of two lists as your input.

> Here, let's pass earnings and prices to create a two-dimensional array.

In [40]:
nested_list =\
[
         [10.09, 10.28, 2.21,   6.19,   8.24],
         [99.98, 87.68, 154.23, 162.12, 121.11]
        ]

nested_list

[[10.09, 10.28, 2.21, 6.19, 8.24], [99.98, 87.68, 154.23, 162.12, 121.11]]

In [43]:
nested_list[1][1]

87.68

In [41]:
np.array(nested_list)

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [39]:
pe_array =\
(
    np
    .array(
        [
         [10.09, 10.28, 2.21,   6.19,   8.24],
         [99.98, 87.68, 154.23, 162.12, 121.11]
        ]
    )
)

print(pe_array)

# Recall that there were two lists of earnings_list and prices_list


[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [44]:
np.array(nested_list) == pe_array

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

> You might want to use `boolean` arrays as well. 

> As you will see below, Boolean arrays are quite useful for subsetting--stay tuned :)

#### Methods in Array

In [45]:
dir(pe_array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [46]:
help(pe_array.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None, *, keepdims=False)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



> Like list, array also has many useful methods.

##### array.shape

In [47]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [48]:
pe_array.shape # returns row, column

(2, 5)

##### array.size

In [49]:
np\
    .size(pe_array)

10

In [50]:
pe_array.size

10

##### array.transpose

In [52]:
pe_array_TRANSPOSED =\
    np\
    .transpose(pe_array)

pe_array_TRANSPOSED.shape

(5, 2)

In [53]:
pe_array_TRANSPOSED

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

> Remember how to subset nested lists? Subsetting two-dimensional arrays is similar to subsetting nested lists. 

> In a 2D array, the indexing/slicing should be specific to the dimension of the array: **`array[row, column]`**

##### How would you subset `earnings` from the `transposed pe_array`? 

In [54]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [55]:
earnings_ARRAY =\
(
    pe_array[ 0 , : ]
     #      row, column
# when transposed row becomes column; column becomes row
)

earnings_ARRAY

array([10.09, 10.28,  2.21,  6.19,  8.24])

In [56]:
earnings_ARRAY == pe_array_TRANSPOSED[ : , 0 ]

array([ True,  True,  True,  True,  True])

In [57]:
len(earnings_ARRAY == pe_array_TRANSPOSED[ : , 0 ]
   )

5

##### How would you subset `prices` from the `transposed pe_array`? 

In [58]:
prices_ARRAY =\
(
    pe_array_TRANSPOSED[ : , 1 ]
                      #  R , C
)

prices_ARRAY

array([ 99.98,  87.68, 154.23, 162.12, 121.11])

##### How would you subset the `earnings and prices for third and forth companies` from the `transposed pe_array`?

In [59]:
pe_array_TRANSPOSED

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

In [60]:
pe_array_TRANSPOSED[2:4, : ] == pe_array_TRANSPOSED[2:-1, : ]

array([[ True,  True],
       [ True,  True]])

In [61]:
pe_SUBSET = pe_array_TRANSPOSED[2:4, : ]

In [62]:
pe_SUBSET == pe_array[ : , 2:4]

array([[ True, False],
       [False,  True]])

> ***Review & Expansion of Your Vocabulary: Below are some useful basics for array.***

In [64]:
# Get Dimension
earnings_ARRAY.ndim == 1

True

In [66]:
pe_array.ndim == pe_array_TRANSPOSED.ndim

True

In [67]:
# Get Shape
pe_array.shape

(2, 5)

In [68]:
# Get Type
pe_array.dtype

dtype('float64')

In [70]:
# Get number of elements (size)
pe_array.size # returns 10

10

In [69]:
# Get Size (individual item size)
pe_array.itemsize

8

In [71]:
# Get total size (in bytes)
pe_array.nbytes

80

In [73]:
# Get a specific element [row, column]
len(pe_array[ : , 0] == pe_array[ : , 2]
   )

2

In [74]:
# Get a specific row 
pe_array[1, :]

array([ 99.98,  87.68, 154.23, 162.12, 121.11])

In [75]:
# Get a specific column
pe_array[ : , 4]

array([  8.24, 121.11])

In [76]:
# Getting a little more fancy [startindex:endindex:stepsize]
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [77]:
pe_array_TRANSPOSED

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

In [78]:
pe_array_TRANSPOSED[0:-1:3, 0  ]
         # np.ARRAY[Row   , Col]

array([10.09,  6.19])

#### `WARNING`: Please be careful when `copying arrays`!

In [79]:
help(pe_array.copy)

Help on built-in function copy:

copy(...) method of numpy.ndarray instance
    a.copy(order='C')
    
    Return a copy of the array.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout of the copy. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible. (Note that this function and :func:`numpy.copy` are very
        similar but have different default values for their order=
        arguments, and this function always passes sub-classes through.)
    
    See also
    --------
    numpy.copy : Similar function with different default behavior
    numpy.copyto
    
    Notes
    -----
    This function is the preferred method for creating an array copy.  The
    function :func:`numpy.copy` is similar, but it defaults to using order 'K',
    and will not pass sub-classes through by default.
    
    Exampl

In [80]:
p =\
(
    np
    .array(
        [2, 4, 6]
    )
)

In [81]:
q = p

In [82]:
p[-1] = 8
p

array([2, 4, 8])

In [83]:
q

array([2, 4, 8])

In [84]:
x = np.array([1, 3, 5])
y = x.copy() # .copy() generates a DEEP copy of the array (it is stored with its own data in memory)

x[-1] = 7
print(x);print(y)

[1 3 7]
[1 3 5]


### Mathematics with NumPy

> **`We all love mathematics`. For a lot more**, [check this out](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

- For example, `linear algebra`, look at [here](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html).

#### Statistics

> Not only can you perform element-wise calculations on NumPy arrays, you can also calculate summary statistics such as range, mean, and standard deviation of arrays using functions from NumPy.

##### Calculating the range (minimum and maximum values)

In [85]:
print(pe_array)

[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [86]:
pe_array.ndim == 2

True

In [87]:
np.min(pe_array)

2.21

In [88]:
np.max(pe_array)

162.12

In [89]:
np\
    .max(pe_array,
         axis = 0)

array([ 99.98,  87.68, 154.23, 162.12, 121.11])

In [90]:
pe_array.min(axis = 0)

array([10.09, 10.28,  2.21,  6.19,  8.24])

In [91]:
np.min(pe_array,
       axis = 1)

array([ 2.21, 87.68])

##### Calculating the mean (`mean`) and standard deviation (`std`)

In [92]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [93]:
earnings_mean =\
(
    np
    .mean(pe_array
          [0 , : ]
         )
)

print(earnings_mean)

7.401999999999999


In [94]:
prices_std =\
(
    np
    .std(pe_array_TRANSPOSED[ : , 1]
        )
)

print(prices_std)

29.210269837849836


In [95]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [96]:
np.mean(pe_array[0, :])

7.401999999999999

In [97]:
np.mean(pe_array, axis = 0)

array([55.035, 48.98 , 78.22 , 84.155, 64.675])

In [98]:
pe_array[1 , :].std()

29.210269837849836

In [99]:
np.std(pe_array_TRANSPOSED[ : , 1]) == pe_array.std(axis = 0)

array([False, False, False, False, False])

In [100]:
%ls

2016_census_data.csv
QF627_PreCourse_01_Introduction_REview.ipynb
QF627_PreCourse_02_NumPy_InProgress_2.ipynb
QF627_PreCourse_03_matplotlib_Preview.ipynb
QF627_PreCourse_03_pandas_Part1_Preview.ipynb
countries.csv
matplotlib.png
ndim.png


##### Generating a sequence of numbers

> Often you may want to create an array of a range of numbers (e.g., 1 to 500) without having to type in every single number. 

> The NumPy function `arange()` is an efficient way to create numeric arrays of a range of numbers--using arange() can be much faster than typing each individual element.

> The arguments for `arange()` include the `start`, `stop`, and `step interval` as follows: `np.arange(start, stop, step)`


In [101]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [102]:
ticker_ids =\
(
    np
    .arange(1, 1001, 1)
)

In [103]:
print(ticker_ids)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  177  178  179  180  181  182
  183  184  185  186  187  188  189  190  191  192  193  194  195  196
  197 

> How would you create `odd numbers only`?

In [104]:
ticker_ids_odd =\
(
    np
    .arange(1, 1001, 2)
)

print(ticker_ids_odd)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

> How would you create **`even`** numbers only then? 

In [105]:
ticker_ids_even = ticker_ids_odd + 1
print(ticker_ids_even)

[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
   30   32   34   36   38   40   42   44   46   48   50   52   54   56
   58   60   62   64   66   68   70   72   74   76   78   80   82   84
   86   88   90   92   94   96   98  100  102  104  106  108  110  112
  114  116  118  120  122  124  126  128  130  132  134  136  138  140
  142  144  146  148  150  152  154  156  158  160  162  164  166  168
  170  172  174  176  178  180  182  184  186  188  190  192  194  196
  198  200  202  204  206  208  210  212  214  216  218  220  222  224
  226  228  230  232  234  236  238  240  242  244  246  248  250  252
  254  256  258  260  262  264  266  268  270  272  274  276  278  280
  282  284  286  288  290  292  294  296  298  300  302  304  306  308
  310  312  314  316  318  320  322  324  326  328  330  332  334  336
  338  340  342  344  346  348  350  352  354  356  358  360  362  364
  366  368  370  372  374  376  378  380  382  384  386  388  390  392
  394 

#### Boolean arrays can be a very powerful way to subset arrays. 

> As a case in point, let's try to identify the earnings that are greater than average from a list of earnings.

> To do so, let's find the mean value of earnings first.

In [106]:
%whos

Variable                Type       Data/Info
--------------------------------------------
a_list                  list       n=4
an_array                ndarray    4: 4 elems, type `<U21`, 336 bytes
earnings_ARRAY          ndarray    5: 5 elems, type `float64`, 40 bytes
earnings_ARRAY_SUBSET   ndarray    3: 3 elems, type `float64`, 24 bytes
earnings_list           list       n=5
earnings_list_SUBSET    list       n=3
earnings_mean           float64    7.401999999999999
element_wise_list       list       n=5
first_object            float      121.11
list_A                  list       n=3
list_B                  list       n=3
nested_list             list       n=2
np                      module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy                   module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
p                       ndarray    3: 3 elems, type `int64`, 24 bytes
pe_SUBSET               ndarray    2x2: 4 elems, type `float64`, 32 bytes
pe

In [107]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [108]:
earnings_ARRAY == pe_array[0, :]

array([ True,  True,  True,  True,  True])

In [109]:
earnings_AVERAGE =\
(
    np
    .mean(earnings_ARRAY)
)

earnings_AVERAGE

7.401999999999999

##### How would you index earnings that are lesser than average

> Hint: You might want to create a boolean array first.

In [113]:
boolean_array =\
(
    earnings_AVERAGE > earnings_ARRAY
)

In [114]:
print(boolean_array)

[False False  True  True False]


In [116]:
earings_below_mean =\
(
    earnings_ARRAY
    [earnings_AVERAGE > earnings_ARRAY]    
)

print(earings_below_mean)

[2.21 6.19]


In [117]:
earings_below_mean == earnings_ARRAY[boolean_array]

array([ True,  True])

## Time Value of Money with `numpy_financial`

In [118]:
!pip install numpy-financial


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [119]:
import numpy_financial as npf

In [120]:
%whos

Variable                Type       Data/Info
--------------------------------------------
a_list                  list       n=4
an_array                ndarray    4: 4 elems, type `<U21`, 336 bytes
boolean_array           ndarray    5: 5 elems, type `bool`, 5 bytes
earings_below_mean      ndarray    2: 2 elems, type `float64`, 16 bytes
earnings_ARRAY          ndarray    5: 5 elems, type `float64`, 40 bytes
earnings_ARRAY_SUBSET   ndarray    3: 3 elems, type `float64`, 24 bytes
earnings_AVERAGE        float64    7.401999999999999
earnings_list           list       n=5
earnings_list_SUBSET    list       n=3
earnings_mean           float64    7.401999999999999
element_wise_list       list       n=5
first_object            float      121.11
list_A                  list       n=3
list_B                  list       n=3
nested_list             list       n=2
np                      module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
npf                     module     <module '

> For your information, there is numpy_financial package that contains a collection of elementary financial functions. 

> It will make your life easier when working with financial values.

> For example, the function .pv(rate, nper, pmt, fv) allows you to calculate the present value of an investment with some parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period
- `fv` The future value of the investment

> You can use this formula in many ways (e.g., you can calculate the present value of future investments in today's dollars).

In [121]:
invest_case =\
(
    npf
    .pv(rate = 0.06,
        nper = 12,
        pmt = 0,
        fv = 50e3)
)

> Before you run the code above, you should have installed the package `numpy-financial`.

> Here, the present value returned is negative, so we multiply the result by -1

In [123]:
print("Your investment is worth "
      + str(round(-invest_case, 1)
           )
      + " in today's dollars."
     )

Your investment is worth 24848.5 in today's dollars.


In [124]:
help(npf.fv)

Help on function fv in module numpy_financial._financial:

fv(rate, nper, pmt, pv, when='end')
    Compute the future value.
    
    Given:
     * a present value, `pv`
     * an interest `rate` compounded once per period, of which
       there are
     * `nper` total
     * a (fixed) payment, `pmt`, paid either
     * at the beginning (`when` = {'begin', 1}) or the end
       (`when` = {'end', 0}) of each period
    
    Return:
       the value at the end of the `nper` periods
    
    Parameters
    ----------
    rate : scalar or array_like of shape(M, )
        Rate of interest as decimal (not per cent) per period
    nper : scalar or array_like of shape(M, )
        Number of compounding periods
    pmt : scalar or array_like of shape(M, )
        Payment
    pv : scalar or array_like of shape(M, )
        Present value
    when : {{'begin', 1}, {'end', 0}}, {string, int}, optional
        When payments are due ('begin' (1) or 'end' (0)).
        Defaults to {'end', 0}.
    
   

> Similarly, you can also calculate the future value of an investment the following parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period (which is 0 in our example)
- `pv` The present value of the investment

> Here, you can use the function .fv(rate, nper, pmt, pv).

> Note that you should `input a negative value into the pv parameter` if it represents `a negative cash flow (cash going out)`. 

> That is, if you were to compute the future value of an investment, requiring an up-front cash payment, you would need to `input a negative value to the pv parameter` in the function .fv().

# Estimate Your Investment's Future Value

In [126]:
invest_fv =\
(
    npf
    .fv(rate = 0.04,
        nper = 9,
        pmt = 0,
        pv = -60e3)
)

print("Your investment will return a total of "
      + str(round(invest_fv, 1)
           )
      + " dollars in 9 years.")

Your investment will return a total of 85398.7 dollars in 9 years.


# Estimate the Future Value of Your Friend's Investment

##### Now let's adjust future values of your investment for inflation with the following steps:

**1. forecast the future value of an investment given a rate of return**

**2. discount the future value of the investment by a projected inflation rate**

> Here, we will `utilize both functions .fv() and .pv()` to estimate the projected value of a given investment in today's dollars, adjusted for inflation.

> ***Scenario***: `Investment returning 7% per year for 25 years`

In [128]:
friend_invesment =\
(
    npf
    .fv(rate = 0.07,
        nper = 25,
        pmt = 0,
        pv = -75e3)
)

print("Your friend's investment will return of a total "
      + str(round(friend_invesment, 1)
           )
      + " dollars in 25 years."
     )

Your friend's investment will return of a total 407057.4 dollars in 25 years.


> ***Scenario***: `Inflation rate of 2.5% per year for 25 years`

In [129]:
discount =\
(
    npf
    .pv(rate = 0.025,
        nper = 25,
        pmt = 0,
        fv = friend_invesment)
)

print("After adjusting for inflation, your friend's investment is worth of "
      + str(round(-discount, 1)
           )
      + " dollars in today's dollars."
     )

After adjusting for inflation, your friend's investment is worth of 219563.0 dollars in today's dollars.


> `Thank you for working with the script :)`